name: madden_ratings_update

on:
  schedule:
      - cron: '0 0 * * *'

jobs:
  update_ratings:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install packages
        run: Rscript -e 'install.packages(c("nflfastR","dplyr","jsonlite","janitor","readr"))'
      - name: Update ratings data
        run: Rscript madden/update_madden_ratings.R
